### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Marchantia1** [Philooz/pyambientmixer#1]
Thanks for providing this! However, I get an error when running ambient_downloader.py, related to the url name?

```
$ python ambient_downloader.py http://religion.ambient-mixer.com/night-in-a-medieval-monastery
Traceback (most recent call last):
  File "ambient_downloader.py", line 69, in <module>
    download_sounds(get_correct_file(arguments.get('<url>')))
  File "ambient_downloader.py", line 46, in get_correct_file
    val = re_js_reg.findall(str(page))[0]
IndexError: list index out of range
```

This on Manjaro with Python 3.7.2 as the default python.

**Comment by Philooz** [comment]
Hi !
I'm going to look at it as soon as possible. :)
Thanks for downloading it!

**Comment by Philooz** [comment]
Fixed. Thanks !

**Comment by Marchantia1** [comment]
That was quick :) Works for me now. Awesome!

**Comment by Philooz** [comment]
A pleasure ! Glad this script is of use. ;)
